version: 2.1

workflows:
  build_pyabr: 
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build: 
    docker:
      - image: cimg/python:3.8
      
    steps:
      - checkout
      - restore_cache:
            key: deps-{{ checksum "requirements.txt" }}
      - run:
          name: Download Deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
            
      - run:
          name: Build test
          command: |
            . venv/bin/activate
            python3 build.py
