version: 2.1

workflows:
  build_pyabr: 
    jobs:
      - build

jobs:
  build: 
    docker:
      - image: cimg/python:3.8
      
    steps:
      - run:
          name: Download Deps
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirments.txt
            
      - run:
          name: Build test
          command: |
            source venv/bin/activate
            python3 build.py
